# Generated by Django 2.2 on 2019-09-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='task_status',
            field=models.CharField(choices=[('To do', 'To do'), ('In progress', 'In progress'), ('Rejected', 'Rejected'), ('Done', 'Done'), ('Postponed', 'Postponed')], default='To do', max_length=255),
        ),
    ]
