# Generated by Django 2.2 on 2019-09-28 00:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0002_todotask'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotask',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
