# Generated by Django 2.2 on 2019-10-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0002_auto_20190930_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quotes', models.CharField(max_length=16384)),
                ('authors', models.CharField(max_length=2048)),
            ],
        ),
    ]
